# Base configuration for AI Development Orchestrator

app_name: "AI Development Orchestrator"
app_version: "0.1.0"
debug: false

# Server configuration
host: "0.0.0.0"
port: 8000
workers: 1

# Database configuration
database:
  url: "postgresql://localhost:5432/ai_orchestrator"
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Redis configuration  
redis:
  url: "redis://localhost:6379/0"
  max_connections: 20
  retry_on_timeout: true

# AI provider configuration
ai:
  provider: "claude"
  model: "claude-3-sonnet-20240229"
  max_tokens: 4000
  temperature: 0.7
  timeout: 60

# Security configuration
security:
  jwt_algorithm: "HS256"
  jwt_expiry_hours: 24
  max_login_attempts: 5
  lockout_duration_minutes: 30

# Workspace configuration
workspace:
  base_path: "/tmp/ai-orchestrator-workspaces"
  max_workspaces: 50
  cleanup_after_hours: 24
  max_disk_usage_gb: 100

# Monitoring configuration
monitoring:
  log_level: "INFO"
  log_format: "json"
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 60