# Development environment overrides

debug: true

# Development database
database:
  url: "postgresql://localhost:5432/ai_orchestrator_dev"
  pool_size: 5

# Development AI settings
ai:
  max_tokens: 2000
  temperature: 0.8

# Development workspace settings
workspace:
  base_path: "/tmp/ai-orchestrator-dev-workspaces"
  max_workspaces: 10

# Development monitoring
monitoring:
  log_level: "DEBUG"
  log_format: "text"
  enable_metrics: false