# Production environment overrides

debug: false

# Production server settings
workers: 4
host: "0.0.0.0"
port: 8000

# Production database
database:
  pool_size: 20
  max_overflow: 40

# Production Redis
redis:
  max_connections: 50

# Production workspace settings  
workspace:
  max_workspaces: 100
  max_disk_usage_gb: 500

# Production monitoring
monitoring:
  log_level: "INFO" 
  log_format: "json"
  enable_metrics: true
  health_check_interval: 30