# Example Configuration: Jira + GitHub + Slack Setup
# =============================================================================
# This configuration shows how to set up the AI Development Automation System
# with Jira for task management, GitHub for version control, and Slack for communication

# System Configuration
system:
  name: "Development Team AI Orchestrator"
  version: "1.0.0"
  environment: "production"
  workspace_dir: "./workspaces"
  max_concurrent_agents: 3

# AI Provider - Using Anthropic Claude
ai_provider:
  primary:
    type: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    api_key: "${ANTHROPIC_API_KEY}"
    max_tokens: 100000
    temperature: 0.7
  
  limits:
    max_cost_per_task: 8.00
    max_tokens_per_task: 75000
    monthly_budget: 800.00

# Plugin Configuration
plugins:
  
  # Jira for Task Management
  task_management:
    provider: "jira"
    enabled: true
    config_file: "./plugins/jira.config.yaml"
    timeout: 30
    retry_attempts: 3
  
  # GitHub for Version Control
  version_control:
    provider: "github"
    enabled: true
    config_file: "./plugins/github.config.yaml"
    timeout: 45
    retry_attempts: 3
  
  # Slack for Communication
  communication:
    provider: "slack"
    enabled: true
    config_file: "./plugins/slack.config.yaml"
    timeout: 15
    retry_attempts: 3

# Workflow Configuration
workflows:
  default_workflow: "jira_github_dev_workflow"
  workflow_dir: "./workflows"
  
  # Custom workflow for Jira + GitHub
  jira_github_dev_workflow:
    enabled: true
    auto_assign: false
    require_approval: true
    notification_channels: ["slack"]

# Agent Configuration
agents:
  planning_agent:
    enabled: true
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 8000
    timeout: 300
    cost_limit: 15.00
    
  development_agent:
    enabled: true
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 8000
    timeout: 1800
    cost_limit: 25.00

# Security Configuration
security:
  require_approval_for_merge: true
  sandbox_agents: true
  allowed_file_types: [".py", ".js", ".ts", ".java", ".go", ".rs", ".cpp", ".h", ".json", ".yaml", ".yml", ".md", ".txt"]

# Team-Specific Configuration
custom:
  company:
    name: "Acme Development Corp"
    domain: "acme.com"
    timezone: "America/New_York"
    
  teams:
    default_reviewers: ["tech-lead@acme.com", "senior-dev@acme.com"]
    required_approvals: 2
    auto_assign_reviewers: true
    
  quality:
    min_test_coverage: 0.85
    required_linting: true
    security_scan: true
    
  deployment:
    auto_deploy_staging: true
    auto_deploy_production: false
    staging_branch: "develop"
    production_branch: "main"

# Notification Configuration
notifications:
  default_channels: ["slack"]
  
  events:
    task_assigned:
      enabled: true
      channels: ["slack"]
      template: "jira_task_assigned"
      
    pr_created:
      enabled: true
      channels: ["slack"]
      template: "github_pr_created"
      
    agent_failed:
      enabled: true
      channels: ["slack", "email"]
      template: "agent_failure"
      urgency: "high"

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    include_business_metrics: true
    
  alerts:
    enabled: true
    channels: ["slack"]
    thresholds:
      error_rate: 0.05
      response_time: 10000
      monthly_budget_usage: 0.9

# Environment-Specific Settings
environments:
  production:
    logging:
      level: "INFO"
    security:
      ip_whitelist:
        enabled: true
        allowed_ips: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
    backup:
      enabled: true
      retention_days: 90